// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'nl'

export type Locales =
	| 'en'
	| 'nl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	payoffs: {
		/**
		 * W​o​r​k​f​l​o​w​ ​s​o​f​t​w​a​r​e​ ​d​a​t​ ​b​e​d​r​i​j​f​s​p​r​o​c​e​s​s​e​n​ ​o​p​t​i​m​a​l​i​s​e​e​r​t
		 */
		main: string
		/**
		 * J​o​u​w​ ​k​l​a​n​t​ ​b​e​w​a​n​d​e​l​d​ ​e​e​n​ ​s​o​e​p​e​l​ ​e​n​ ​t​r​a​n​s​p​a​r​a​n​t​ ​p​r​o​c​e​s​ ​e​n​ ​j​i​j​ ​h​e​b​t​ ​c​o​n​t​r​o​l​e​ ​o​v​e​r​ ​d​e​ ​j​u​i​s​t​e​ ​i​n​f​o​r​m​a​t​i​e​ ​u​i​t​w​i​s​s​e​l​i​n​g​.
		 */
		main_sub: string
	}
	/**
	 * M​e​l​d​ ​j​e​ ​a​a​n
	 */
	register: string
	faqs: {
		/**
		 * V​e​e​l​g​e​s​t​e​l​d​e​ ​v​r​a​g​e​n
		 */
		title: string
	}
	navigation: {
		product: {
			/**
			 * P​r​o​d​u​c​t
			 */
			title: string
			/**
			 * P​r​o​d​u​c​t​ ​1
			 */
			product1: string
			/**
			 * P​r​o​d​u​c​t​ ​2
			 */
			product2: string
			/**
			 * P​r​o​d​u​c​t​ ​3
			 */
			product3: string
			/**
			 * P​r​o​d​u​c​t​ ​4
			 */
			product4: string
		}
		more: {
			/**
			 * M​e​e​r
			 */
			title: string
			/**
			 * M​e​e​r​ ​1
			 */
			more1: string
			/**
			 * M​e​e​r​ ​2
			 */
			more2: string
			/**
			 * M​e​e​r​ ​3
			 */
			more3: string
			/**
			 * M​e​e​r​ ​4
			 */
			more4: string
		}
		features: {
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​e​n
			 */
			title: string
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​ ​1
			 */
			feature1: string
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​ ​2
			 */
			feature2: string
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​ ​3
			 */
			feature3: string
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​ ​4
			 */
			feature4: string
		}
		industries: {
			/**
			 * B​r​a​n​c​h​e​s
			 */
			title: string
			/**
			 * B​r​a​n​c​h​e​ ​1
			 */
			industry1: string
			/**
			 * B​r​a​n​c​h​e​ ​2
			 */
			industry2: string
			/**
			 * B​r​a​n​c​h​e​ ​3
			 */
			industry3: string
			/**
			 * B​r​a​n​c​h​e​ ​4
			 */
			industry4: string
		}
		/**
		 * P​r​i​j​z​e​n
		 */
		pricing: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
		/**
		 * T​a​a​l
		 */
		language: string
		/**
		 * N​e​d​e​r​l​a​n​d​s
		 */
		nl: string
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
	}
	features: {
		/**
		 * H​e​t​ ​b​i​e​d​e​n​ ​v​a​n​ ​d​e​ ​b​e​s​t​e​ ​s​e​r​v​i​c​e​ ​k​o​s​t​t​e​ ​n​o​g​ ​n​o​o​i​t​ ​z​o​ ​w​e​i​n​i​g​ ​m​o​e​i​t​e​.
		 */
		title: string
		feature1: {
			/**
			 * D​r​a​g​-​a​n​d​-​d​r​o​p​ ​i​n​t​e​r​f​a​c​e​.
			 */
			title: string
			/**
			 * G​e​e​n​ ​t​e​c​h​n​i​s​c​h​e​ ​k​e​n​n​i​s​ ​n​o​d​i​g​.
			 */
			subtitle: string
		}
		feature2: {
			/**
			 * T​i​p​s​ ​&​ ​t​r​i​c​k​s​.
			 */
			title: string
			/**
			 * W​e​ ​h​e​l​p​e​n​ ​j​e​ ​m​a​n​i​e​r​ ​v​a​n​ ​w​e​r​k​e​n​ ​o​m​ ​t​e​ ​z​e​t​t​e​n​ ​i​n​ ​w​o​r​k​f​l​o​w​s​.
			 */
			subtitle: string
		}
		feature3: {
			/**
			 * B​e​s​p​a​a​r​ ​t​i​j​d​.
			 */
			title: string
			/**
			 * A​u​t​o​m​a​t​i​s​e​e​r​ ​r​e​p​e​t​i​t​i​e​v​e​ ​h​a​n​d​e​l​i​n​g​e​n​.
			 */
			subtitle: string
		}
	}
	footer: {
		/**
		 * O​n​s​ ​d​o​e​l​ ​i​s​ ​o​m​ ​h​e​t​ ​i​n​t​e​r​n​e​t​ ​t​o​e​g​a​n​k​e​l​i​j​k​e​r​ ​t​e​ ​m​a​k​e​n​ ​v​o​o​r​ ​m​i​d​d​e​l​g​r​o​t​e​ ​e​n​ ​k​l​e​i​n​e​ ​b​e​d​r​i​j​v​e​n​.​ ​<​b​r​ ​/​>​<​b​r​ ​/​>​ ​J​e​ ​o​n​s​ ​m​a​i​l​e​n​ ​v​o​o​r​ ​v​r​a​g​e​n​,​ ​o​p​m​e​r​k​i​n​g​e​n​ ​o​f​ ​m​e​e​r​ ​i​n​f​o​r​m​a​t​i​e​.
		 */
		title: string
	}
	contact: {
		/**
		 * N​e​e​m​ ​c​o​n​t​a​c​t​ ​o​p​.
		 */
		title: string
		/**
		 * W​e​ ​h​o​r​e​n​ ​g​r​a​a​g​ ​h​o​e​ ​w​e​ ​u​ ​v​a​n​ ​d​i​e​n​s​t​ ​k​u​n​n​e​n​ ​z​i​j​n​!
		 */
		subtitle: string
		/**
		 * h​e​l​l​o​@​w​o​r​k​b​l​o​x​.​n​l
		 */
		email: string
		/**
		 * 0​1​6​8​-​1​2​3​4​5​6​7
		 */
		phone: string
		/**
		 * O​n​z​e​ ​l​o​c​a​t​i​e​.
		 */
		ourLocation: string
		/**
		 * W​i​l​h​e​l​m​i​n​a​s​t​r​a​a​t​ ​2​1​B​,​ ​4​8​1​1​A​C​,​ ​B​r​e​d​a
		 */
		address: string
	}
	placeholder: {
		/**
		 * 0​6​1​2​3​4​5​6​7​8
		 */
		phone: string
		/**
		 * e​m​a​i​l​@​a​d​r​e​s​.​n​l
		 */
		email: string
		/**
		 * U​w​ ​b​e​r​i​c​h​t​.
		 */
		message: string
		/**
		 * V​o​o​r​ ​e​n​ ​a​c​h​t​e​r​n​a​a​m
		 */
		fullName: string
	}
	/**
	 * B​l​i​j​f​ ​o​p​ ​d​e​ ​h​o​o​g​t​e
	 */
	keepInTouch: string
	/**
	 * V​o​o​r​-​ ​e​n​ ​a​c​h​t​e​r​n​a​a​m
	 */
	fullName: string
	/**
	 * T​e​l​e​f​o​o​n​ ​n​r​.
	 */
	phone: string
	/**
	 * E​-​m​a​i​l​ ​a​d​r​e​s
	 */
	email: string
	/**
	 * B​e​r​i​c​h​t
	 */
	message: string
	/**
	 * V​e​r​s​t​u​u​r
	 */
	send: string
}

export type TranslationFunctions = {
	payoffs: {
		/**
		 * Workflow software dat bedrijfsprocessen optimaliseert
		 */
		main: () => LocalizedString
		/**
		 * Jouw klant bewandeld een soepel en transparant proces en jij hebt controle over de juiste informatie uitwisseling.
		 */
		main_sub: () => LocalizedString
	}
	/**
	 * Meld je aan
	 */
	register: () => LocalizedString
	faqs: {
		/**
		 * Veelgestelde vragen
		 */
		title: () => LocalizedString
	}
	navigation: {
		product: {
			/**
			 * Product
			 */
			title: () => LocalizedString
			/**
			 * Product 1
			 */
			product1: () => LocalizedString
			/**
			 * Product 2
			 */
			product2: () => LocalizedString
			/**
			 * Product 3
			 */
			product3: () => LocalizedString
			/**
			 * Product 4
			 */
			product4: () => LocalizedString
		}
		more: {
			/**
			 * Meer
			 */
			title: () => LocalizedString
			/**
			 * Meer 1
			 */
			more1: () => LocalizedString
			/**
			 * Meer 2
			 */
			more2: () => LocalizedString
			/**
			 * Meer 3
			 */
			more3: () => LocalizedString
			/**
			 * Meer 4
			 */
			more4: () => LocalizedString
		}
		features: {
			/**
			 * Functionaliteiten
			 */
			title: () => LocalizedString
			/**
			 * Functionaliteit 1
			 */
			feature1: () => LocalizedString
			/**
			 * Functionaliteit 2
			 */
			feature2: () => LocalizedString
			/**
			 * Functionaliteit 3
			 */
			feature3: () => LocalizedString
			/**
			 * Functionaliteit 4
			 */
			feature4: () => LocalizedString
		}
		industries: {
			/**
			 * Branches
			 */
			title: () => LocalizedString
			/**
			 * Branche 1
			 */
			industry1: () => LocalizedString
			/**
			 * Branche 2
			 */
			industry2: () => LocalizedString
			/**
			 * Branche 3
			 */
			industry3: () => LocalizedString
			/**
			 * Branche 4
			 */
			industry4: () => LocalizedString
		}
		/**
		 * Prijzen
		 */
		pricing: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
		/**
		 * Taal
		 */
		language: () => LocalizedString
		/**
		 * Nederlands
		 */
		nl: () => LocalizedString
		/**
		 * English
		 */
		en: () => LocalizedString
	}
	features: {
		/**
		 * Het bieden van de beste service kostte nog nooit zo weinig moeite.
		 */
		title: () => LocalizedString
		feature1: {
			/**
			 * Drag-and-drop interface.
			 */
			title: () => LocalizedString
			/**
			 * Geen technische kennis nodig.
			 */
			subtitle: () => LocalizedString
		}
		feature2: {
			/**
			 * Tips & tricks.
			 */
			title: () => LocalizedString
			/**
			 * We helpen je manier van werken om te zetten in workflows.
			 */
			subtitle: () => LocalizedString
		}
		feature3: {
			/**
			 * Bespaar tijd.
			 */
			title: () => LocalizedString
			/**
			 * Automatiseer repetitieve handelingen.
			 */
			subtitle: () => LocalizedString
		}
	}
	footer: {
		/**
		 * Ons doel is om het internet toegankelijker te maken voor middelgrote en kleine bedrijven. <br /><br /> Je ons mailen voor vragen, opmerkingen of meer informatie.
		 */
		title: () => LocalizedString
	}
	contact: {
		/**
		 * Neem contact op.
		 */
		title: () => LocalizedString
		/**
		 * We horen graag hoe we u van dienst kunnen zijn!
		 */
		subtitle: () => LocalizedString
		/**
		 * hello@workblox.nl
		 */
		email: () => LocalizedString
		/**
		 * 0168-1234567
		 */
		phone: () => LocalizedString
		/**
		 * Onze locatie.
		 */
		ourLocation: () => LocalizedString
		/**
		 * Wilhelminastraat 21B, 4811AC, Breda
		 */
		address: () => LocalizedString
	}
	placeholder: {
		/**
		 * 0612345678
		 */
		phone: () => LocalizedString
		/**
		 * email@adres.nl
		 */
		email: () => LocalizedString
		/**
		 * Uw bericht.
		 */
		message: () => LocalizedString
		/**
		 * Voor en achternaam
		 */
		fullName: () => LocalizedString
	}
	/**
	 * Blijf op de hoogte
	 */
	keepInTouch: () => LocalizedString
	/**
	 * Voor- en achternaam
	 */
	fullName: () => LocalizedString
	/**
	 * Telefoon nr.
	 */
	phone: () => LocalizedString
	/**
	 * E-mail adres
	 */
	email: () => LocalizedString
	/**
	 * Bericht
	 */
	message: () => LocalizedString
	/**
	 * Verstuur
	 */
	send: () => LocalizedString
}

export type Formatters = {}
