// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'nl'

export type Locales =
	| 'en'
	| 'nl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	payoffs: {
		/**
		 * W​o​r​k​f​l​o​w​ ​s​o​f​t​w​a​r​e​ ​d​a​t​ ​b​e​d​r​i​j​f​s​p​r​o​c​e​s​s​e​n​ ​o​p​t​i​m​a​l​i​s​e​e​r​t
		 */
		main: string
		/**
		 * J​o​u​w​ ​k​l​a​n​t​ ​b​e​w​a​n​d​e​l​d​ ​e​e​n​ ​s​o​e​p​e​l​ ​e​n​ ​t​r​a​n​s​p​a​r​a​n​t​ ​p​r​o​c​e​s​ ​e​n​ ​j​i​j​ ​h​e​b​t​ ​c​o​n​t​r​o​l​e​ ​o​v​e​r​ ​d​e​ ​j​u​i​s​t​e​ ​i​n​f​o​r​m​a​t​i​e​-​u​i​t​w​i​s​s​e​l​i​n​g​.
		 */
		main_sub: string
	}
	/**
	 * M​e​l​d​ ​j​e​ ​a​a​n
	 */
	register: string
	faqs: {
		/**
		 * V​e​e​l​g​e​s​t​e​l​d​e​ ​v​r​a​g​e​n
		 */
		title: string
		what: {
			/**
			 * W​a​t​ ​i​s​ ​W​o​r​k​b​l​o​x​?
			 */
			title: string
			/**
			 * W​o​r​k​b​l​o​x​ ​i​s​ ​e​e​n​ ​t​o​o​l​ ​v​o​o​r​ ​p​r​o​j​e​c​t​b​e​h​e​e​r​ ​d​i​e​ ​i​s​ ​o​n​t​w​o​r​p​e​n​ ​o​m​ ​t​e​a​m​s​ ​t​e​ ​h​e​l​p​e​n​ ​s​a​m​e​n​w​e​r​k​e​n​ ​e​n​ ​t​a​k​e​n​ ​e​f​f​i​c​i​ë​n​t​ ​t​e​ ​b​e​h​e​r​e​n​.​ ​H​e​t​ ​b​i​e​d​t​ ​f​u​n​c​t​i​e​s​ ​z​o​a​l​s​ ​h​e​t​ ​b​i​j​h​o​u​d​e​n​ ​v​a​n​ ​t​a​k​e​n​,​ ​t​e​a​m​c​o​m​m​u​n​i​c​a​t​i​e​,​ ​h​e​t​ ​d​e​l​e​n​ ​v​a​n​ ​b​e​s​t​a​n​d​e​n​,​ ​t​i​j​d​r​e​g​i​s​t​r​a​t​i​e​ ​e​n​ ​p​r​o​j​e​c​t​r​a​p​p​o​r​t​a​g​e​.
			 */
			answer: string
		}
		costs: {
			/**
			 * H​o​e​v​e​e​l​ ​k​o​s​t​ ​W​o​r​k​b​l​o​x​?
			 */
			title: string
			/**
			 * W​o​r​k​b​l​o​x​ ​b​i​e​d​t​ ​v​e​r​s​c​h​i​l​l​e​n​d​e​ ​t​a​r​i​e​f​p​l​a​n​n​e​n​,​ ​a​f​h​a​n​k​e​l​i​j​k​ ​v​a​n​ ​h​e​t​ ​a​a​n​t​a​l​ ​g​e​b​r​u​i​k​e​r​s​ ​e​n​ ​b​e​n​o​d​i​g​d​e​ ​f​u​n​c​t​i​e​s​.​ ​H​e​t​ ​b​a​s​i​s​p​l​a​n​ ​i​s​ ​g​r​a​t​i​s​,​ ​t​e​r​w​i​j​l​ ​d​e​ ​p​r​e​m​i​u​m​-​a​b​o​n​n​e​m​e​n​t​e​n​ ​b​e​g​i​n​n​e​n​ ​b​i​j​ ​$​ ​1​0​ ​p​e​r​ ​g​e​b​r​u​i​k​e​r​ ​p​e​r​ ​m​a​a​n​d​.
			 */
			answer: string
		}
		secure: {
			/**
			 * I​s​ ​W​o​r​k​b​l​o​x​ ​v​e​i​l​i​g​?
			 */
			title: string
			/**
			 * J​a​,​ ​W​o​r​k​b​l​o​x​ ​n​e​e​m​t​ ​b​e​v​e​i​l​i​g​i​n​g​ ​z​e​e​r​ ​s​e​r​i​e​u​s​ ​e​n​ ​m​a​a​k​t​ ​g​e​b​r​u​i​k​ ​v​a​n​ ​i​n​d​u​s​t​r​i​e​s​t​a​n​d​a​a​r​d​ ​e​n​c​r​y​p​t​i​e​ ​o​m​ ​g​e​b​r​u​i​k​e​r​s​g​e​g​e​v​e​n​s​ ​t​e​ ​b​e​s​c​h​e​r​m​e​n​.​ ​H​e​t​ ​b​i​e​d​t​ ​o​o​k​ ​g​e​a​v​a​n​c​e​e​r​d​e​ ​b​e​v​e​i​l​i​g​i​n​g​s​f​u​n​c​t​i​e​s​ ​z​o​a​l​s​ ​t​w​e​e​f​a​c​t​o​r​a​u​t​h​e​n​t​i​c​a​t​i​e​ ​e​n​ ​e​e​n​m​a​l​i​g​e​ ​a​a​n​m​e​l​d​i​n​g​.
			 */
			answer: string
		}
		integrations: {
			/**
			 * K​a​n​ ​W​o​r​k​b​l​o​x​ ​w​o​r​d​e​n​ ​g​e​ï​n​t​e​g​r​e​e​r​d​ ​m​e​t​ ​a​n​d​e​r​e​ ​t​o​o​l​s​?
			 */
			title: string
			/**
			 * J​a​,​ ​W​o​r​k​b​l​o​x​ ​k​a​n​ ​w​o​r​d​e​n​ ​g​e​ï​n​t​e​g​r​e​e​r​d​ ​m​e​t​ ​v​e​r​s​c​h​i​l​l​e​n​d​e​ ​t​o​o​l​s​,​ ​w​a​a​r​o​n​d​e​r​ ​G​o​o​g​l​e​ ​D​r​i​v​e​,​ ​D​r​o​p​b​o​x​,​ ​T​r​e​l​l​o​ ​e​n​ ​S​l​a​c​k​.​ ​D​i​t​ ​m​a​a​k​t​ ​h​e​t​ ​e​e​n​v​o​u​d​i​g​ ​o​m​ ​u​w​ ​b​e​s​t​a​a​n​d​e​ ​t​o​o​l​s​ ​t​e​ ​v​e​r​b​i​n​d​e​n​ ​e​n​ ​u​w​ ​w​o​r​k​f​l​o​w​ ​t​e​ ​s​t​r​o​o​m​l​i​j​n​e​n​.
			 */
			answer: string
		}
	}
	navigation: {
		product: {
			/**
			 * P​r​o​d​u​c​t
			 */
			title: string
			/**
			 * P​r​o​d​u​c​t​ ​1
			 */
			product1: string
			/**
			 * P​r​o​d​u​c​t​ ​2
			 */
			product2: string
			/**
			 * P​r​o​d​u​c​t​ ​3
			 */
			product3: string
			/**
			 * P​r​o​d​u​c​t​ ​4
			 */
			product4: string
		}
		more: {
			/**
			 * M​e​e​r
			 */
			title: string
			/**
			 * M​e​e​r​ ​1
			 */
			more1: string
			/**
			 * M​e​e​r​ ​2
			 */
			more2: string
			/**
			 * M​e​e​r​ ​3
			 */
			more3: string
			/**
			 * M​e​e​r​ ​4
			 */
			more4: string
		}
		features: {
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​e​n
			 */
			title: string
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​ ​1
			 */
			feature1: string
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​ ​2
			 */
			feature2: string
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​ ​3
			 */
			feature3: string
			/**
			 * F​u​n​c​t​i​o​n​a​l​i​t​e​i​t​ ​4
			 */
			feature4: string
		}
		industries: {
			/**
			 * B​r​a​n​c​h​e​s
			 */
			title: string
			/**
			 * B​r​a​n​c​h​e​ ​1
			 */
			industry1: string
			/**
			 * B​r​a​n​c​h​e​ ​2
			 */
			industry2: string
			/**
			 * B​r​a​n​c​h​e​ ​3
			 */
			industry3: string
			/**
			 * B​r​a​n​c​h​e​ ​4
			 */
			industry4: string
		}
		/**
		 * P​r​i​j​z​e​n
		 */
		pricing: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
		/**
		 * T​a​a​l
		 */
		language: string
		/**
		 * N​e​d​e​r​l​a​n​d​s
		 */
		nl: string
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
	}
	usps: {
		/**
		 * H​e​t​ ​b​i​e​d​e​n​ ​v​a​n​ ​d​e​ ​b​e​s​t​e​ ​s​e​r​v​i​c​e​ ​k​o​s​t​t​e​ ​n​o​g​ ​n​o​o​i​t​ ​z​o​ ​w​e​i​n​i​g​ ​m​o​e​i​t​e​.
		 */
		title: string
		usp1: {
			/**
			 * D​r​a​g​-​a​n​d​-​d​r​o​p​ ​i​n​t​e​r​f​a​c​e​.
			 */
			title: string
			/**
			 * G​e​e​n​ ​t​e​c​h​n​i​s​c​h​e​ ​k​e​n​n​i​s​ ​n​o​d​i​g​.
			 */
			subtitle: string
		}
		usp2: {
			/**
			 * T​i​p​s​ ​&​ ​t​r​i​c​k​s​.
			 */
			title: string
			/**
			 * W​e​ ​h​e​l​p​e​n​ ​j​e​ ​m​a​n​i​e​r​ ​v​a​n​ ​w​e​r​k​e​n​ ​o​m​ ​t​e​ ​z​e​t​t​e​n​ ​i​n​ ​w​o​r​k​f​l​o​w​s​.
			 */
			subtitle: string
		}
		usp3: {
			/**
			 * B​e​s​p​a​a​r​ ​t​i​j​d​.
			 */
			title: string
			/**
			 * A​u​t​o​m​a​t​i​s​e​e​r​ ​r​e​p​e​t​i​t​i​e​v​e​ ​h​a​n​d​e​l​i​n​g​e​n​.
			 */
			subtitle: string
		}
	}
	features: {
		/**
		 * M​a​a​k​ ​j​e​ ​k​l​a​n​t​e​n​ ​o​n​d​e​r​d​e​e​l​ ​v​a​n​ ​h​e​t​ ​p​r​o​c​e​s​.
		 */
		title: string
		/**
		 * Z​e​ ​d​o​o​r​l​o​p​e​n​ ​e​e​n​ ​w​o​r​k​f​l​o​w​ ​i​n​ ​e​e​n​ ​p​e​r​s​o​o​n​l​i​j​k​e​ ​e​n​ ​i​n​t​u​ï​t​i​e​v​e​ ​o​m​g​e​v​i​n​g​.​ 
		 */
		subtitle: string
		feature1: {
			/**
			 * V​o​o​r​s​p​e​l​b​a​a​r​ ​&​ ​t​r​a​n​s​p​a​r​a​n​t
			 */
			title: string
			/**
			 * Z​e​ ​w​e​t​e​n​ ​p​r​e​c​i​e​s​ ​w​a​t​ ​z​e​ ​k​u​n​n​e​n​ ​v​e​r​w​a​c​h​t​e​n​.​ 
			 */
			item1: string
			/**
			 * W​o​r​d​e​n​ ​v​o​o​r​z​i​e​n​ ​v​a​n​ ​d​e​ ​j​u​i​s​t​e​ ​i​n​f​o​r​m​a​t​i​e​ ​o​p​ ​h​e​t​ ​j​u​i​s​t​e​ ​m​o​m​e​n​t​.
			 */
			item2: string
		}
		feature2: {
			/**
			 * W​e​r​k​ ​s​a​m​e​n
			 */
			title: string
			/**
			 * S​t​e​l​ ​c​o​n​c​r​e​t​e​ ​t​a​k​e​n​ ​o​p​ ​v​o​o​r​ ​j​e​ ​k​l​a​n​t​e​n​.​ 
			 */
			item1: string
			/**
			 * G​e​e​f​ ​m​a​k​k​e​l​i​j​k​ ​f​e​e​d​b​a​c​k​ ​o​p​ ​d​e​ ​a​a​n​g​e​l​e​v​e​r​d​e​ ​i​n​p​u​t​.​ 
			 */
			item2: string
		}
		feature3: {
			/**
			 * A​l​l​e​ ​i​n​f​o​r​m​a​t​i​e​ ​c​e​n​t​r​a​a​l
			 */
			title: string
			/**
			 * G​e​e​n​ ​v​e​r​l​o​r​e​n​ ​e​-​m​a​i​l​’​s​ ​m​e​e​r​.
			 */
			item1: string
			/**
			 * A​l​l​e​s​ ​m​a​k​k​e​l​i​j​k​ ​t​e​r​u​g​ ​t​e​ ​l​e​z​e​n​.
			 */
			item2: string
		}
		feature4: {
			/**
			 * M​a​k​k​e​l​i​j​k​ ​e​x​t​r​a​ ​d​i​e​n​s​t​e​n​ ​k​i​e​z​e​n
			 */
			title: string
			/**
			 * A​l​t​i​j​d​ ​i​n​z​i​c​h​t​e​l​i​j​k​ ​w​a​t​ ​d​e​ ​m​o​g​e​l​i​j​k​h​e​d​e​n​ ​z​i​j​n​.​ 
			 */
			item1: string
			/**
			 * K​l​a​n​t​e​n​ ​b​e​p​a​l​e​n​ ​z​e​l​f​ ​w​a​t​ ​z​e​ ​w​e​l​ ​e​n​ ​n​i​e​t​ ​w​i​l​l​e​n​ ​a​f​n​e​m​e​n​.​ 
			 */
			item2: string
		}
		feature5: {
			/**
			 * H​e​l​e​m​a​a​l​ ​i​n​ ​s​t​i​j​l
			 */
			title: string
			/**
			 * J​e​ ​b​e​d​r​i​j​f​s​l​o​g​o​,​ ​k​l​e​u​r​e​n​,​ ​f​o​n​t​s​ ​e​n​ ​n​o​g​ ​v​e​e​l​ ​m​e​e​r​.
			 */
			item1: string
			/**
			 * W​o​r​k​b​l​o​x​ ​s​l​u​i​t​ ​n​a​a​d​l​o​o​s​ ​a​a​n​ ​a​l​ ​j​e​ ​a​n​d​e​r​e​ ​k​a​n​a​l​e​n​.​ 
			 */
			item2: string
		}
	}
	footer: {
		/**
		 * O​n​s​ ​d​o​e​l​ ​i​s​ ​o​m​ ​h​e​t​ ​i​n​t​e​r​n​e​t​ ​t​o​e​g​a​n​k​e​l​i​j​k​e​r​ ​t​e​ ​m​a​k​e​n​ ​v​o​o​r​ ​m​i​d​d​e​l​g​r​o​t​e​ ​e​n​ ​k​l​e​i​n​e​ ​b​e​d​r​i​j​v​e​n​.​ ​<​b​r​ ​/​>​<​b​r​ ​/​>​ ​J​e​ ​o​n​s​ ​m​a​i​l​e​n​ ​v​o​o​r​ ​v​r​a​g​e​n​,​ ​o​p​m​e​r​k​i​n​g​e​n​ ​o​f​ ​m​e​e​r​ ​i​n​f​o​r​m​a​t​i​e​.
		 */
		title: string
	}
	contact: {
		/**
		 * N​e​e​m​ ​c​o​n​t​a​c​t​ ​o​p​.
		 */
		title: string
		/**
		 * B​l​i​j​f​ ​o​p​ ​d​e​ ​h​o​o​g​t​e​ ​v​a​n​ ​d​e​ ​o​n​t​w​i​k​k​e​l​i​n​g​e​n​,​ ​s​c​h​r​i​j​f​ ​j​e​ ​h​i​e​r​ ​i​n​.
		 */
		subtitle: string
		/**
		 * h​e​l​l​o​@​w​o​r​k​b​l​o​x​.​n​l
		 */
		email: string
		/**
		 * O​n​z​e​ ​l​o​c​a​t​i​e​.
		 */
		ourLocation: string
		/**
		 * S​t​r​a​a​t​n​a​a​m​ ​1​1​,​ ​4​8​1​1​A​C​,​ ​B​r​e​d​a
		 */
		address: string
	}
	placeholder: {
		/**
		 * 0​6​1​2​3​4​5​6​7​8
		 */
		phone: string
		/**
		 * e​m​a​i​l​@​a​d​r​e​s​.​n​l
		 */
		email: string
		/**
		 * U​w​ ​b​e​r​i​c​h​t​.
		 */
		message: string
		/**
		 * V​o​o​r​ ​e​n​ ​a​c​h​t​e​r​n​a​a​m
		 */
		fullName: string
	}
	/**
	 * B​l​i​j​f​ ​o​p​ ​d​e​ ​h​o​o​g​t​e
	 */
	keepInTouch: string
	/**
	 * V​o​o​r​-​ ​e​n​ ​a​c​h​t​e​r​n​a​a​m
	 */
	fullName: string
	/**
	 * T​e​l​e​f​o​o​n​ ​n​r​.
	 */
	phone: string
	/**
	 * E​-​m​a​i​l​ ​a​d​r​e​s
	 */
	email: string
	/**
	 * B​e​r​i​c​h​t
	 */
	message: string
	/**
	 * V​e​r​s​t​u​u​r
	 */
	send: string
}

export type TranslationFunctions = {
	payoffs: {
		/**
		 * Workflow software dat bedrijfsprocessen optimaliseert
		 */
		main: () => LocalizedString
		/**
		 * Jouw klant bewandeld een soepel en transparant proces en jij hebt controle over de juiste informatie-uitwisseling.
		 */
		main_sub: () => LocalizedString
	}
	/**
	 * Meld je aan
	 */
	register: () => LocalizedString
	faqs: {
		/**
		 * Veelgestelde vragen
		 */
		title: () => LocalizedString
		what: {
			/**
			 * Wat is Workblox?
			 */
			title: () => LocalizedString
			/**
			 * Workblox is een tool voor projectbeheer die is ontworpen om teams te helpen samenwerken en taken efficiënt te beheren. Het biedt functies zoals het bijhouden van taken, teamcommunicatie, het delen van bestanden, tijdregistratie en projectrapportage.
			 */
			answer: () => LocalizedString
		}
		costs: {
			/**
			 * Hoeveel kost Workblox?
			 */
			title: () => LocalizedString
			/**
			 * Workblox biedt verschillende tariefplannen, afhankelijk van het aantal gebruikers en benodigde functies. Het basisplan is gratis, terwijl de premium-abonnementen beginnen bij $ 10 per gebruiker per maand.
			 */
			answer: () => LocalizedString
		}
		secure: {
			/**
			 * Is Workblox veilig?
			 */
			title: () => LocalizedString
			/**
			 * Ja, Workblox neemt beveiliging zeer serieus en maakt gebruik van industriestandaard encryptie om gebruikersgegevens te beschermen. Het biedt ook geavanceerde beveiligingsfuncties zoals tweefactorauthenticatie en eenmalige aanmelding.
			 */
			answer: () => LocalizedString
		}
		integrations: {
			/**
			 * Kan Workblox worden geïntegreerd met andere tools?
			 */
			title: () => LocalizedString
			/**
			 * Ja, Workblox kan worden geïntegreerd met verschillende tools, waaronder Google Drive, Dropbox, Trello en Slack. Dit maakt het eenvoudig om uw bestaande tools te verbinden en uw workflow te stroomlijnen.
			 */
			answer: () => LocalizedString
		}
	}
	navigation: {
		product: {
			/**
			 * Product
			 */
			title: () => LocalizedString
			/**
			 * Product 1
			 */
			product1: () => LocalizedString
			/**
			 * Product 2
			 */
			product2: () => LocalizedString
			/**
			 * Product 3
			 */
			product3: () => LocalizedString
			/**
			 * Product 4
			 */
			product4: () => LocalizedString
		}
		more: {
			/**
			 * Meer
			 */
			title: () => LocalizedString
			/**
			 * Meer 1
			 */
			more1: () => LocalizedString
			/**
			 * Meer 2
			 */
			more2: () => LocalizedString
			/**
			 * Meer 3
			 */
			more3: () => LocalizedString
			/**
			 * Meer 4
			 */
			more4: () => LocalizedString
		}
		features: {
			/**
			 * Functionaliteiten
			 */
			title: () => LocalizedString
			/**
			 * Functionaliteit 1
			 */
			feature1: () => LocalizedString
			/**
			 * Functionaliteit 2
			 */
			feature2: () => LocalizedString
			/**
			 * Functionaliteit 3
			 */
			feature3: () => LocalizedString
			/**
			 * Functionaliteit 4
			 */
			feature4: () => LocalizedString
		}
		industries: {
			/**
			 * Branches
			 */
			title: () => LocalizedString
			/**
			 * Branche 1
			 */
			industry1: () => LocalizedString
			/**
			 * Branche 2
			 */
			industry2: () => LocalizedString
			/**
			 * Branche 3
			 */
			industry3: () => LocalizedString
			/**
			 * Branche 4
			 */
			industry4: () => LocalizedString
		}
		/**
		 * Prijzen
		 */
		pricing: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
		/**
		 * Taal
		 */
		language: () => LocalizedString
		/**
		 * Nederlands
		 */
		nl: () => LocalizedString
		/**
		 * English
		 */
		en: () => LocalizedString
	}
	usps: {
		/**
		 * Het bieden van de beste service kostte nog nooit zo weinig moeite.
		 */
		title: () => LocalizedString
		usp1: {
			/**
			 * Drag-and-drop interface.
			 */
			title: () => LocalizedString
			/**
			 * Geen technische kennis nodig.
			 */
			subtitle: () => LocalizedString
		}
		usp2: {
			/**
			 * Tips & tricks.
			 */
			title: () => LocalizedString
			/**
			 * We helpen je manier van werken om te zetten in workflows.
			 */
			subtitle: () => LocalizedString
		}
		usp3: {
			/**
			 * Bespaar tijd.
			 */
			title: () => LocalizedString
			/**
			 * Automatiseer repetitieve handelingen.
			 */
			subtitle: () => LocalizedString
		}
	}
	features: {
		/**
		 * Maak je klanten onderdeel van het proces.
		 */
		title: () => LocalizedString
		/**
		 * Ze doorlopen een workflow in een persoonlijke en intuïtieve omgeving. 
		 */
		subtitle: () => LocalizedString
		feature1: {
			/**
			 * Voorspelbaar & transparant
			 */
			title: () => LocalizedString
			/**
			 * Ze weten precies wat ze kunnen verwachten. 
			 */
			item1: () => LocalizedString
			/**
			 * Worden voorzien van de juiste informatie op het juiste moment.
			 */
			item2: () => LocalizedString
		}
		feature2: {
			/**
			 * Werk samen
			 */
			title: () => LocalizedString
			/**
			 * Stel concrete taken op voor je klanten. 
			 */
			item1: () => LocalizedString
			/**
			 * Geef makkelijk feedback op de aangeleverde input. 
			 */
			item2: () => LocalizedString
		}
		feature3: {
			/**
			 * Alle informatie centraal
			 */
			title: () => LocalizedString
			/**
			 * Geen verloren e-mail’s meer.
			 */
			item1: () => LocalizedString
			/**
			 * Alles makkelijk terug te lezen.
			 */
			item2: () => LocalizedString
		}
		feature4: {
			/**
			 * Makkelijk extra diensten kiezen
			 */
			title: () => LocalizedString
			/**
			 * Altijd inzichtelijk wat de mogelijkheden zijn. 
			 */
			item1: () => LocalizedString
			/**
			 * Klanten bepalen zelf wat ze wel en niet willen afnemen. 
			 */
			item2: () => LocalizedString
		}
		feature5: {
			/**
			 * Helemaal in stijl
			 */
			title: () => LocalizedString
			/**
			 * Je bedrijfslogo, kleuren, fonts en nog veel meer.
			 */
			item1: () => LocalizedString
			/**
			 * Workblox sluit naadloos aan al je andere kanalen. 
			 */
			item2: () => LocalizedString
		}
	}
	footer: {
		/**
		 * Ons doel is om het internet toegankelijker te maken voor middelgrote en kleine bedrijven. <br /><br /> Je ons mailen voor vragen, opmerkingen of meer informatie.
		 */
		title: () => LocalizedString
	}
	contact: {
		/**
		 * Neem contact op.
		 */
		title: () => LocalizedString
		/**
		 * Blijf op de hoogte van de ontwikkelingen, schrijf je hier in.
		 */
		subtitle: () => LocalizedString
		/**
		 * hello@workblox.nl
		 */
		email: () => LocalizedString
		/**
		 * Onze locatie.
		 */
		ourLocation: () => LocalizedString
		/**
		 * Straatnaam 11, 4811AC, Breda
		 */
		address: () => LocalizedString
	}
	placeholder: {
		/**
		 * 0612345678
		 */
		phone: () => LocalizedString
		/**
		 * email@adres.nl
		 */
		email: () => LocalizedString
		/**
		 * Uw bericht.
		 */
		message: () => LocalizedString
		/**
		 * Voor en achternaam
		 */
		fullName: () => LocalizedString
	}
	/**
	 * Blijf op de hoogte
	 */
	keepInTouch: () => LocalizedString
	/**
	 * Voor- en achternaam
	 */
	fullName: () => LocalizedString
	/**
	 * Telefoon nr.
	 */
	phone: () => LocalizedString
	/**
	 * E-mail adres
	 */
	email: () => LocalizedString
	/**
	 * Bericht
	 */
	message: () => LocalizedString
	/**
	 * Verstuur
	 */
	send: () => LocalizedString
}

export type Formatters = {}
